<?php
/**
 * @file
 * Code for the bHack modifications feature.
 */

// Features include.
include_once 'bhack_modifications.features.inc';

/**
 * Implements hook_theme().
 */
function bhack_modifications_theme() {
  $items['page__eform__submit__register_interest'] = array(
    'render element' => 'page',
    'template' => 'templates/page__eform__submit__register_interest',
  );

  return $items;
}

/**
 * Implements hook_preprocess_page().
 */
function bhack_modifications_preprocess_page(&$vars) {
  if (drupal_is_front_page()) {
    $base = drupal_get_path('module', 'bhack_modifications') . '/assets';
    drupal_add_css('https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css', array('type' => 'external'));
    drupal_add_css($base . '/css/animate.css');
    drupal_add_css($base . '/css/style.css');
    drupal_add_css($base . '/css/style-responsive.css');
    drupal_add_css($base . '/third/vegas/jquery.vegas.min.css');

    drupal_add_js($base . '/js/jquery.smooth-scroll.js');
    drupal_add_js($base . '/third/mixitup/jquery.mixitup.js');
    drupal_add_js($base . '/third/vegas/jquery.vegas.min.js');
    drupal_add_js($base . '/js/bhack.js');
  }
}

/**
 * Implements hook_html_head_alter().
 */
function bhack_modifications_html_head_alter(&$head_elements) {
  foreach ($head_elements as &$element) {
    if (isset($element['#attributes']['rel']) && 'shortcut icon' == $element['#attributes']['rel']) {
      $element['#attributes']['href'] = drupal_get_path('module', 'bhack_modifications') . '/images/favicon.ico';
    }
  }
}
